# Visualising Results
## Overview
Outline what I'm doing. 
```{r setup, include=FALSE}
setwd("C:/Users/Jana/Desktop/tara_iti")

library(tidyr)
library(ggplot2)
#install.packages("devtools")
#devtools::install_github("G-Thomson/Manu")
library(Manu)

pal <- get_pal("Kotare")
get_pal("Kotare")
print_pal(pal)
```
## Heterozygosity
Individual heterozygosity as estimated by ANGSD.  
```{r heterozygosity, include=FALSE}
indiv_het <- read.csv("angsd/heterozygosity_summary.tsv", sep="\t", header = TRUE)

pdf("plots/SNP_heterozygosity.pdf")
ggplot(indiv_het, aes(x=Population, y = Heterozygosity, fill = Tool)) +
    geom_violin() +
    theme_light() +
    labs(x = "Population", y = "Observed Heterozygosity", title = "Individual Heterozygosity") +
    scale_fill_manual(values = c("gatk" = "#E5BF86","samtools" = "#287DAB")) 
dev.off()
```

### Runs of Homozygosity
Create a one-column file (e.g., scat_rohs.txt) with ROH sizes across all samples
These ROH sizes were obtained from above after excluding microchromosomal scaffolds
```{r ROH clusters, include=FALSE}
library(mclust)
scat_ROH<-read.csv("~/scat_rohs.txt", header = F)
test<-Mclust(scat_ROH)
scatbic<-mclustBIC(scat_ROH)
summary(scatbic, parameter=TRUE)
plot(scatbic)
summary(test, parameter=TRUE)

x<-seq(0,8000000, length=1000)
scag1<-dnorm(x, mean=test$parameters$mean[1], sd=sqrt(test$parameters$variance$sigmasq[1]))
scag2<-dnorm(x, mean=test$parameters$mean[2], sd=sqrt(test$parameters$variance$sigmasq[2]))
scag3<-dnorm(x, mean=test$parameters$mean[3], sd=sqrt(test$parameters$variance$sigmasq[3]))
hist(test$data, breaks=132, main="Distribution of ROH for inbred S. catenatus", xlab="Number of base pairs")
lines(x, (scag1*1800000000), col="red")
lines(x, (scag2*1800000000), col="blue")
lines(x, (scag3*1800000000), col="green")
legend("topright", title="Gaussian groups", legend=c("Short","Medium","Long"), lty=c(1,1,1), col=c("red", "blue", "green"))

hist(test$data, breaks=132, main="Distribution of ROH for S. catenatus", xlab="Number of base pairs")
abline(v=200000, lty=5, col="red")
abline(v=700000, lty=4, col="blue")
legend("topright", title="ROH boundries", legend=c("Short-Medium break","Medium-Long break"), lty=c(5,4), col=c("red", "blue"))

plot(x,scag1, col="red", type="l", main="ROH length distributions for S. catenatus",
     xlab="Number of base pairs", ylab="", yaxt="n")
lines(x, (scag2), col="blue")
lines(x, (scag3), col="green")
legend("topright", title="Gaussian groups", legend=c("Short","Medium","Long"), lty=c(1,1,1), col=c("red", "blue", "green"))
```